import json
from dataclasses import dataclass
from typing import Protocol

from rag.generation.prompt_builder import (
    SYSTEM_PROMPT,
    build_user_prompt,
)
from rag.retrieval.retriever import RetrievedChunk


class LLMClient(Protocol):
    """
    Interface implemented by an LLM provider adapter.

    Generator depends on this abstraction rather than on Gemini,
    OpenAI, or any other provider directly.
    """

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a text response from an LLM.
        """
        ...


@dataclass(frozen=True)
class Citation:
    """
    Trusted citation created from retrieved chunk metadata.

    The LLM only selects source_id. Filename, page number,
    and chunk index always come from our retrieval system.
    """

    source_id: int
    filename: str
    page_number: int
    chunk_index: int


@dataclass
class GeneratedAnswer:
    """
    Structured output returned by the generation layer.

    answer:
        Natural-language answer generated by the LLM.

    citations:
        Validated citations derived from retrieved chunks.

    sources:
        Full retrieved context used during generation. Useful
        later for debugging, observability, and API responses.
    """

    answer: str
    citations: list[Citation]
    sources: list[RetrievedChunk]


class Generator:
    """
    Generate grounded answers and validate LLM citations.
    """

    def __init__(
        self,
        llm_client: LLMClient,
    ) -> None:
        self.llm_client = llm_client

    def generate(
        self,
        query: str,
        chunks: list[RetrievedChunk],
    ) -> GeneratedAnswer:
        """
        Generate an answer from retrieved context.

        The LLM returns source numbers only. This method validates
        those source numbers and maps them back to trusted chunk
        metadata such as filename and page number.
        """

        if not query.strip():
            raise ValueError(
                "Query cannot be empty"
            )

        user_prompt = build_user_prompt(
            query=query,
            chunks=chunks,
        )

        raw_response = self.llm_client.generate(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

        if not raw_response.strip():
            raise ValueError(
                "LLM returned an empty response"
            )

        response_data = self._parse_response(
            raw_response=raw_response,
        )

        answer = response_data["answer"]
        citation_ids = response_data["citations"]

        citations = self._build_citations(
            citation_ids=citation_ids,
            chunks=chunks,
        )

        return GeneratedAnswer(
            answer=answer,
            citations=citations,
            sources=chunks,
        )

    @staticmethod
    def _parse_response(
        raw_response: str,
    ) -> dict:
        """
        Parse and validate the JSON structure returned by the LLM.

        Expected format:

        {
            "answer": "...",
            "citations": [1, 3]
        }
        """

        cleaned_response = raw_response.strip()

        # Some models may still surround JSON with Markdown fences
        # despite being instructed not to. Remove simple fences so
        # the application can recover safely.
        if cleaned_response.startswith("```"):
            lines = cleaned_response.splitlines()

            if lines:
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            cleaned_response = "\n".join(
                lines
            ).strip()

        try:
            data = json.loads(
                cleaned_response
            )
        except json.JSONDecodeError as exc:
            raise ValueError(
                "LLM returned invalid JSON"
            ) from exc

        if not isinstance(data, dict):
            raise ValueError(
                "LLM response must be a JSON object"
            )

        if set(data.keys()) != {
            "answer",
            "citations",
        }:
            raise ValueError(
                "LLM response must contain exactly "
                "'answer' and 'citations'"
            )

        answer = data["answer"]
        citations = data["citations"]

        if not isinstance(answer, str):
            raise ValueError(
                "LLM response field 'answer' "
                "must be a string"
            )

        if not answer.strip():
            raise ValueError(
                "LLM returned an empty answer"
            )

        if not isinstance(citations, list):
            raise ValueError(
                "LLM response field 'citations' "
                "must be a list"
            )

        if not all(
            isinstance(source_id, int)
            and not isinstance(source_id, bool)
            for source_id in citations
        ):
            raise ValueError(
                "Every citation must be an integer "
                "source ID"
            )

        return {
            "answer": answer.strip(),
            "citations": citations,
        }

    @staticmethod
    def _build_citations(
        citation_ids: list[int],
        chunks: list[RetrievedChunk],
    ) -> list[Citation]:
        """
        Validate LLM-selected source IDs and convert them into
        trusted citation objects.

        The LLM cannot control filename, page number, or chunk
        index. Those fields come directly from retrieval metadata.
        """

        citations: list[Citation] = []

        seen_source_ids: set[int] = set()

        for source_id in citation_ids:
            if source_id < 1:
                raise ValueError(
                    f"Invalid citation source ID: "
                    f"{source_id}"
                )

            if source_id > len(chunks):
                raise ValueError(
                    f"Citation source ID {source_id} "
                    "does not exist in retrieved context"
                )

            # Avoid duplicate citations such as [1, 1, 3].
            if source_id in seen_source_ids:
                continue

            seen_source_ids.add(
                source_id
            )

            chunk = chunks[
                source_id - 1
            ]

            citations.append(
                Citation(
                    source_id=source_id,
                    filename=chunk.filename,
                    page_number=(
                        chunk.page_number
                    ),
                    chunk_index=(
                        chunk.chunk_index
                    ),
                )
            )

        return citations